version: "3"

services:
  phoenix:
    build: .
    container_name: CaloriWeb
    volumes:
      - .:/home/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: /bin/bash
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data