name: Elixir Staging

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Staging environment and deployment
    runs-on: ubuntu-latest
    env:
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Set up Elixir
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        elixir-version: '1.10.3' # Define the elixir version [required]
        otp-version: '22.3' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Release current deployed package - Return one commit and execute a release
      run: |
        git checkout HEAD~1 --quiet
        git log --pretty=oneline -1
        make release

    - name: Release upgrade package - Go to the latest commit and generate an upgrade
      run: |
        git checkout main
        git log --pretty=oneline -1
        make upgrade

    - name: Upload release files to S3
      uses: qoqa/action-s3-cp@v1.1
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'sa-east-1'
        AWS_S3_PATH: '/'
        FILE: '_build/prod/rel/calori_app/releases/0.2.0/calori_app.tar.gz'

